## <div align="center"><b> This file contains the Problem Statement of Numpy Assignment along with their solutions using numpy library. </b></div>

\
\
\
__File name__:  Numpy_Assignment_Solutions
___
__Author__: Arun Kumar Kushwaha
___
__Email__: ark9127@gmail.com
___
__Date created__:  25-Jul-2020
___
__Date last modified__: 26-Jul-2020
___
__Python Version__: 3.7
___

 <hr>______________________________________________________________________________________________________________________________</hr>

__Problem Statement 1:__
Write a function so that the columns of the output matrix are powers of the input vector.

The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.


HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde.

__Solution 1:__

In [77]:
# importing numpy library 

import numpy as np

# creating defination of power_matrix function

def power_matrix(input_vector, col, increasing = True):
    
    row = input_vector.size
        
    if increasing:
        return np.fromfunction(lambda _, j: np.vstack(input_vector)**j,(row,col), dtype = int)
    else:
        return np.fromfunction(lambda _, j: np.vstack(input_vector)**(col-j-1),(row,col), dtype = int)




In [94]:
# initializing input vector and maximum power/no. of columns

input_user = input("Enter the list of integer: ")
input_vector = np.fromstring(input_user,sep = ' ',dtype = int)

max_power = input("Enter the maximum integer power: ")
col_size = int(max_power)+1

print("Column size of output matrix is: ", col_size)


# printing the output matrix having powers of the input vector

output_inc = power_matrix(input_vector,col_size, increasing=True)
output_dec = power_matrix(input_vector,col_size, increasing=False)

print("\nOutput Matrix in increasing order:\n", output_inc)
print("\nOutput Matrix in decreasing order:\n ", output_dec, sep ='')


Enter the list of integer: 1 2 3 4 5
Enter the maximum integer power: 3
Column size of output matrix is:  4

Output Matrix in increasing order:
 [[  1   1   1   1]
 [  1   2   4   8]
 [  1   3   9  27]
 [  1   4  16  64]
 [  1   5  25 125]]

Output Matrix in decreasing order:
 [[  1   1   1   1]
 [  8   4   2   1]
 [ 27   9   3   1]
 [ 64  16   4   1]
 [125  25   5   1]]


 <hr>______________________________________________________________________________________________________________________________</hr>

__Problem Statement 2:__
Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of the given sequence is defined as follows:

The moving average sequence has n-k+1 elements as shown below.

The moving averages with k=4 of a ten-value sequence (n=10) is shown below

i 1 2 3 4 5 6 7 8 9 10

===== == == == == == == == == == ==

Input 10 20 30 40 50 60 70 80 90 100

y1 25 = (10+20+30+40)/4

y2 35 = (20+30+40+50)/4

y3 45 = (30+40+50+60)/4

y4 55 = (40+50+60+70)/4

y5 65 = (50+60+70+80)/4

y6 75 = (60+70+80+90)/4

y7 85 = (70+80+90+100)/4

Thus, the moving average sequence has n-k+1=10-4+1=7 values.

__Query :__
Write a function to find moving average in an array over a window:

Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

__Solution 2:__

In [18]:
# importing numpy library 

import numpy as np

# creating defination of moving_average function

def moving_average(input_vector, w_size):
    
    row = input_vector.size        # storing the size of input vector in row variable
    total_sum = []            # initializing a blank list
    print("\nGiven input vector and it's size is:","\n-------------------------------------")
    print("Input Vector: ", input_vector)
    print("Input Vector Size: ", row)
    print("\nMoving Window Size: ", w_size)
    
    # if condition to make sure the size of moving window is greater than 0
    if (w_size>0 and row>w_size):
        for i in range(row - w_size + 1):
            sum_1 = 0
            for j in range(w_size):
                sum_1 = sum_1 + input_vector[i+j]       # performing addition operation
            sum_1 = sum_1/w_size                        # performing divison operation to calculate the average
            total_sum.append(sum_1)                     # appending the average value in a blank list
        return np.array(total_sum)                      # retuning the moving average array
    elif (w_size<=0):
        return ("\n<<Error>>: The window size should be greater than 0")
    else :
        return ("\n<<Error>>: The window size should be less than the size of input vector")
        



In [19]:
# initializing input vector and size of moving window using user input

input_user = input("Enter the list of integer: ")
input_vector = np.fromstring(input_user,sep = ' ',dtype = int)

win_size = input("Enter the window size greater than 0 and less than the size of above input list: ")
win_size = int(win_size)

# printing the moving average array

avg_array = moving_average(input_vector,win_size)


print("\nThe output of the moving average array is:\n", avg_array)



Enter the list of integer: 1 2 3 4 5 6 7 8
Enter the window size greater than 0 and less than the size of above input list: 3

Given input vector and it's size is: 
-------------------------------------
Input Vector:  [1 2 3 4 5 6 7 8]
Input Vector Size:  8

Moving Window Size:  3

The output of the moving average array is:
 [2. 3. 4. 5. 6. 7.]


In [21]:
# initializing input vector and size of moving window

input_vector_2 = np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])
win_size_2 = 3


# printing the moving average array

avg_array_2 = moving_average(input_vector_2,win_size_2)


print("\nThe output of the moving average array is:\n", avg_array_2)



Given input vector and it's size is: 
-------------------------------------
Input Vector:  [  3   5   7   2   8  10  11  65  72  81  99 100 150]
Input Vector Size:  13

Moving Window Size:  3

The output of the moving average array is:
 [  5.           4.66666667   5.66666667   6.66666667   9.66666667
  28.66666667  49.33333333  72.66666667  84.          93.33333333
 116.33333333]


 <hr>______________________________________________________________________________________________________________________________</hr>